#! /bin/sh
### BEGIN INIT INFO
# Provides:          fuse
# Required-Start:    
# Should-Start:      udev
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Start and stop fuse.
# Description:       Load the fuse module and mount the fuse control
#	filesystem.
### END INIT INFO

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MOUNTPOINT=/sys/fs/fuse/connections

case "$1" in
    start|restart|force-reload)
	mount -t fusectl fusectl $MOUNTPOINT >/dev/null 2>&1
	;;
    stop)
	umount $MOUNTPOINT >/dev/null 2>&1
	;;
    status)
	echo -n "Checking fuse filesystem"
	if ! grep -qw fuse /proc/filesystems; then
		echo " not available."
		exit 3
	else
		echo " ok."
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
