#!/bin/sh

chmod 777 /home/idec/rom
chmod 744 /home/root/idec_init.BIN
chmod 744 /home/root/idec_operation.BIN
chmod 744 /home/root/idec_loader.BIN

VERSION="001.002.000.000"
# Update rootfsB kernel and idec_boot.
# Place the following files in "/home/root" when updating.
BOOT_UPDATE_ARCHIVE="/home/root/boot-update.tar.xz"
RAMDISK="/home/idec/usr/tmp/"
KERNEL_B="${RAMDISK}/uImage"
IDEC_BOOT="${RAMDISK}/idec_boot.BIN"
OSS1="${RAMDISK}/ntfs-3g_2017.3.23-r0_armv7at2hf-neon.tar.xz"
OSS2="${RAMDISK}/ntfsprogs_2017.3.23-r0_armv7at2hf-neon.tar.xz"
UDEV_RULE_B="${RAMDISK}/idec_b.rules"
UPDATE_IMG="${RAMDISK}/boot-update.ppm"
TMP_A_FILE="${RAMDISK}/tmp_a"
terget_debug="0";
version_debug="0";
# decompress boot update archive
if [ ! -e $BOOT_UPDATE_ARCHIVE ]; then
    update-rc.d -f run-postinsts remove
    exit
fi
#check target version
TARGET_VERSION=$(fw_printenv version | cut -f 2 -d "=")
function version1 { echo "$@" | awk -F. '{ printf("%d\n", $1); }'; }
function version2 { echo "$@" | awk -F. '{ printf("%03d%03d\n", $2,$3); }'; }
function version3 { echo "$@" | awk -F. '{ printf("%03d\n", $4); }'; }

if [ $(version3 $VERSION) -eq 0 ]; then
	version_debug="999";
else
	version_debug="$(version3 $VERSION)";
fi
if [ $(version3 $TARGET_VERSION) -eq 0 ]; then
	terget_debug="999";
else
	terget_debug="$(version3 $TARGET_VERSION)";
fi
# if target version >= update version, skip update process
if [ $(version1 $TARGET_VERSION) -eq 1 ]; then
	if [ $(version2 $TARGET_VERSION) -gt $(version2 $VERSION) ]; then
		rm $BOOT_UPDATE_ARCHIVE
		update-rc.d -f run-postinsts remove
	elif [ $(version2 $TARGET_VERSION) -eq $(version2 $VERSION) ]; then
		if [ ${terget_debug} -ge ${version_debug} ]; then
			rm $BOOT_UPDATE_ARCHIVE
			update-rc.d -f run-postinsts remove
		else
			 tar -xf $BOOT_UPDATE_ARCHIVE -C $RAMDISK
		fi
	else
		tar -xf $BOOT_UPDATE_ARCHIVE -C $RAMDISK
	fi
else
	tar -xf $BOOT_UPDATE_ARCHIVE -C $RAMDISK
fi
# Display update image
if [ -e $UPDATE_IMG ]; then
	fbsplash -s $UPDATE_IMG
else
	exit
fi
#check decompressed files
if [ -e $KERNEL_B ]; then
    KERNEL_B_SIZE=`wc -c ${KERNEL_B} | awk '{print $1}'`
# erase KERNEL_B area
    flash_erase /dev/mtd9 0 0

# Update Kernel (rootfsB).
    nandwrite -p /dev/mtd9 $KERNEL_B

# Read Kernel
    nanddump -a /dev/mtd9 -l ${KERNEL_B_SIZE} 1> ${TMP_A_FILE} 2>/dev/null

#verify KERNEL_B
    diff ${KERNEL_B} ${TMP_A_FILE} > /dev/null 2>&1 || exit
    rm $KERNEL_B
    rm $TMP_A_FILE
fi
if [ -e $IDEC_BOOT ]; then
# Update idec_boot.BIN.
    ubiattach.mtd-utils /dev/ubi_ctrl -m 11 -O 512
    mount -t ubifs /dev/ubi1_0 /media/

# atomic update
   cp $IDEC_BOOT /media/home/root/idec_boot.BIN.tmp
   mv /media/home/root/idec_boot.BIN.tmp /media/home/root/idec_boot.BIN
fi
tar xJf $OSS1 -C /media/
tar xJf $OSS2 -C /media/

cp $UDEV_RULE_B /media/etc/udev/rules.d/idec.rules.tmp
mv /media/etc/udev/rules.d/idec.rules.tmp /media/etc/udev/rules.d/idec.rules

sync

umount /media
ubidetach.mtd-utils /dev/ubi_ctrl -m 11
rm $OSS1 
rm $OSS2
rm $UDEV_RULE_B
rm $IDEC_BOOT
# Close dialog
dd if=/dev/zero of=/dev/fb0
rm $UPDATE_IMG

fw_setenv version $VERSION
rm $BOOT_UPDATE_ARCHIVE

# remove script
update-rc.d -f run-postinsts remove
