[core]
require-input=false
gbm-format=rgb565

[shell]
locking=false
animation=none
background-type=none
background-color=0xff000000
panel-position=none
panel-location=""
startup-animation=none
close-animation=none

[input-method]
path=

[screensaver]
# Uncomment path to disable screensaver
#path=@libexecdir@/weston-screensaver
