#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          networking
# Required-Start:    $local_fs mountvirtfs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Raise network interfaces and configure them
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

if ! [ -x /sbin/ifup ]; then
    exit 0
fi

case "$1" in
    start)
        echo -n "Configuring network interfaces... "
        ifup -a
        echo "done."
	;;
    stop)
        echo -n "Deconfiguring network interfaces... "
        ifdown -a
	echo "done."
	;;
    force-reload|restart)
        echo -n "Reconfiguring network interfaces... "
        ifdown -a
        ifup -a
	echo "done."
	;;
    *)
	echo "Usage: /etc/init.d/networking {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0
